export type AppRole = 'student' | 'faculty' | 'admin';

export const strings = {
  meta: {
    title: 'Smart Campus | \u00d6\u011frenci \u0130\u015fleri Paneli',
    lang: 'tr',
    description: 'Smart Campus ile ders, yoklama ve not i\u015flerinizi tek panelden y\u00f6netin.',
    themeColor: '#1f3d7a',
  },
  brand: {
    name: 'Smart Campus',
    tagline: '\u00d6\u011frenci \u0130\u015fleri Paneli',
  },
  roles: {
    student: '\u00d6\u011frenci',
    faculty: 'Akademisyen',
    admin: 'Y\u00f6netici',
  } as Record<AppRole, string>,
  common: {
    userFallback: 'Kullan\u0131c\u0131',
    menuAriaLabel: 'Men\u00fc',
    openMenuLabel: 'Men\u00fcy\u00fc a\u00e7',
    closeMenuLabel: 'Men\u00fcy\u00fc kapat',
    userMenuLabel: 'Kullan\u0131c\u0131 men\u00fcs\u00fc',
    loading: 'Y\u00fckleniyor...',
    format: {
      timeFallback: '--:--',
      dateTimeFallback: '-',
    },
  },
  errors: {
    missingApiBase: {
      title: 'Sunucu ayar\u0131 eksik',
      message: 'VITE_API_BASE_URL tan\u0131ml\u0131 de\u011fil. L\u00fctfen ortam de\u011fi\u015fkenini g\u00fcncelleyip sayfay\u0131 yenileyin.',
      action: 'Sayfay\u0131 yenile',
    },
    boundary: {
      title: 'Bir \u015fey ters gitti',
      description: 'Beklenmeyen bir hata nedeniyle sayfa y\u00fcklenemedi.',
      unexpected: 'Beklenmeyen bir hata olu\u015ftu.',
      reload: 'Sayfay\u0131 yenile',
    },
  },
  navbar: {
    profile: 'Profil',
    logout: '\u00c7\u0131k\u0131\u015f yap',
    login: 'Giri\u015f',
    register: 'Kay\u0131t ol',
  },
  sidebar: {
    sections: {
      general: 'Genel',
      academic: 'Akademik',
      grades: 'Notlar',
      attendance: 'Yoklama',
      campus: 'Kamp\u00fcs Hizmetleri',
      admin: 'Y\u00f6netim',
    },
    items: {
      dashboard: 'Panel',
      profile: 'Profil',
      courses: 'Dersler',
      sections: '\u015eubeler',
      myEnrollments: 'Kay\u0131tlar\u0131m',
      mySchedule: 'Program\u0131m',
      sectionStudents: '\u015eube \u00d6\u011frencileri',
      myGrades: 'Notlar\u0131m',
      transcript: 'Transkript',
      gradeEntry: 'Not Giri\u015fi',
      gradeBulk: 'Toplu Not Giri\u015fi',
      attendanceCheckIn: 'Yoklama Ver',
      attendanceSummary: 'Yoklama \u00d6zeti',
      attendanceExcuse: 'Mazeret G\u00f6nder',
      attendanceSessions: 'Oturumlar',
      attendanceReport: 'Yoklama Raporu',
      attendanceReview: 'Mazeret \u0130ncele',
      meals: 'Yemek Men\u00fcleri',
      cafeterias: 'Yemekhaneler',
      mealReservations: 'Yemek Rezervasyonlar\u0131m',
      mealQrUse: 'Yemek QR Kullan',
      events: 'Etkinlikler',
      eventRegistrations: 'Etkinlik Kay\u0131tlar\u0131m',
      eventCheckIn: 'Etkinlik Check-in',
      wallet: 'C\u00fczdan',
      scheduling: 'Ders Program\u0131m',
      schedulingGenerate: 'Program Olu\u015ftur',
      reservationCreate: 'Derslik Rezervasyonu',
      reservationMine: 'Rezervasyonlar\u0131m',
      reservationRequests: 'Rezervasyon Talepleri',
      courseAdmin: 'Ders Y\u00f6netimi',
      sectionAdmin: '\u015eube Y\u00f6netimi',
      users: 'Kullan\u0131c\u0131lar',
    },
  },
  auth: {
    login: {
      title: 'Tekrar ho\u015f geldiniz',
      subtitle: 'Hesab\u0131n\u0131za giri\u015f yap\u0131n',
      cta: 'Hesab\u0131n yok mu?',
      emailLabel: 'Email',
      emailPlaceholder: 'name@somedomain.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022',
      remember: 'Beni hat\u0131rla',
      forgot: '\u015eifremi unuttum',
      submit: 'Giri\u015f yap',
      submitting: 'Giri\u015f yap\u0131l\u0131yor...',
      error: 'Giri\u015f ba\u015far\u0131s\u0131z.',
    },
    register: {
      title: 'Yeni hesap olu\u015ftur',
      subtitle: '\u00d6\u011frenci veya akademisyen olarak kay\u0131t olun',
      cta: 'Zaten hesab\u0131n\u0131z var m\u0131?',
      success: 'Kay\u0131t ba\u015far\u0131l\u0131. L\u00fctfen e-postan\u0131z\u0131 do\u011frulama i\u00e7in kontrol edin.',
      error: 'Kay\u0131t ba\u015far\u0131s\u0131z.',
      departments: {
        loadError: 'B\u00f6l\u00fcmler y\u00fcklenemedi. L\u00fctfen daha sonra tekrar deneyin.',
        reloadError: 'B\u00f6l\u00fcmler g\u00fcncellenemedi. L\u00fctfen tekrar deneyin.',
      },
      labels: {
        firstName: '\u0130sim',
        lastName: 'Soyisim',
        email: 'E-posta',
        role: 'Rol',
        department: 'B\u00f6l\u00fcm',
        password: '\u015eifre',
        confirmPassword: '\u015eifre Tekrar',
        studentNumber: '\u00d6\u011frenci Numaras\u0131',
        employeeNumber: 'Personel Numaras\u0131',
        title: 'Unvan',
        terms: 'Kullan\u0131m \u015fartlar\u0131n\u0131 kabul ediyorum',
        select: 'Se\u00e7iniz',
      },
      placeholders: {
        firstName: 'Ad\u0131n\u0131z\u0131 girin',
        lastName: 'Soyad\u0131n\u0131z\u0131 girin',
        email: 'ornek@universite.edu.tr',
        password: '********',
        confirmPassword: '********',
        studentNumber: '\u00d6\u011frenci numaran\u0131z',
        employeeNumber: 'Personel numaran\u0131z',
        title: 'Dr. \u00d6\u011fr. \u00dcyesi',
      },
      submit: 'Hesap Olu\u015ftur',
      submitting: 'Kay\u0131t oluyor...',
    },
    forgotPassword: {
      title: '\u015eifre S\u0131f\u0131rlama',
      subtitle: 'E-posta adresinizi girin; kay\u0131tl\u0131ysa s\u0131f\u0131rlama linki g\u00f6nderilecektir.',
      success: 'E\u011fer bu e-posta kay\u0131tl\u0131ysa, \u015fifre s\u0131f\u0131rlama linki g\u00f6nderildi.',
      error: '\u0130\u015flem s\u0131ras\u0131nda bir hata olu\u015ftu.',
      submit: 'S\u0131f\u0131rlama linki g\u00f6nder',
      submitting: 'G\u00f6nderiliyor...',
      backToLogin: 'Giri\u015f sayfas\u0131na d\u00f6n',
      emailPlaceholder: 'ornek@kampus.com',
    },
    resetPassword: {
      title: 'Yeni \u015eifre Belirle',
      subtitle: 'G\u00fc\u00e7l\u00fc bir \u015fifre olu\u015fturun.',
      success: '\u015eifreniz g\u00fcncellendi. Giri\u015f sayfas\u0131na y\u00f6nlendiriliyorsunuz...',
      error: '\u015eifre g\u00fcncellenemedi.',
      submit: '\u015eifreyi G\u00fcncelle',
      submitting: 'G\u00fcncelleniyor...',
      passwordLabel: 'Yeni \u015eifre',
      confirmLabel: 'Yeni \u015eifre Tekrar',
      backToLogin: 'Giri\u015f sayfas\u0131na d\u00f6n',
    },
    verifyEmail: {
      title: 'E-posta Do\u011frulama',
      subtitle: 'Hesab\u0131n\u0131z\u0131 do\u011fruluyoruz.',
      success: 'E-posta do\u011fruland\u0131, birka\u00e7 saniye i\u00e7inde giri\u015f sayfas\u0131na y\u00f6nlendirileceksiniz.',
      error: 'Ge\u00e7ersiz veya s\u00fcresi dolmu\u015f do\u011frulama linki.',
      loading: 'Do\u011frulan\u0131yor...',
    },
  },
  dashboard: {
    error: 'Dashboard verileri al\u0131n\u0131rken bir hata olu\u015ftu.',
    header: {
      greeting: 'Ho\u015f geldin',
      subtitles: {
        student: 'Kay\u0131tl\u0131 derslerin, notlar\u0131n ve yoklama \u00f6zetin burada.',
        faculty: '\u015eubeler, yoklama ve not i\u015flemleri i\u00e7in h\u0131zl\u0131 \u00f6zet.',
        admin: 'Kamp\u00fcsteki metrikler, sistem durumu ve son hareketler.',
        fallback: 'G\u00fcncel bilgiler ve i\u015flemler burada.',
      },
    },
    trend: {
      up: 'Art\u0131\u015f',
      down: 'D\u00fc\u015f\u00fc\u015f',
    },
    quickActions: {
      student: [
        { label: 'Program\u0131n\u0131 g\u00f6r', to: '/enrollments/schedule' },
        { label: 'Yoklama ver', to: '/attendance/checkin' },
      ],
      faculty: [
        { label: 'Oturumlar', to: '/attendance/sessions' },
        { label: 'Not giri\u015fi', to: '/faculty/grades/entry' },
      ],
      admin: [
        { label: 'Kullan\u0131c\u0131lar', to: '/admin/users' },
        { label: 'Ders y\u00f6netimi', to: '/admin/courses/new' },
      ],
    },
    labels: {
      section: '\u015eube',
      planned: 'Planl\u0131',
      awaiting: 'Bekliyor',
      inProgress: 'Devam ediyor',
      upcoming: 'Yakla\u015fan',
      midterm: 'Vize',
      final: 'Final',
      gradePoint: 'Not Ort.',
      updatedAt: 'G\u00fcncelleme',
    },
    student: {
      stats: {
        courses: { label: 'Kay\u0131tl\u0131 Ders', helper: 'Aktif ve tamamlanan kay\u0131tlar' },
        gpa: { label: 'GPA', helperPrefix: 'CGPA' },
        attendance: { label: 'Devam Oran\u0131', helper: 'Genel ortalama' },
        today: { label: 'Bug\u00fcnk\u00fc Ders', helper: 'G\u00fcn\u00fcn program\u0131' },
      },
      sections: {
        todayClasses: {
          title: 'Bug\u00fcnk\u00fc dersler',
          action: 'Ders program\u0131n\u0131 a\u00e7',
          emptyTitle: 'Bug\u00fcn ders yok',
          emptyDescription: 'Takvimine yeni ders eklenince burada g\u00f6rebilirsin.',
          emptyAction: 'Program\u0131n\u0131 g\u00f6r',
        },
        recentGrades: {
          title: 'Son notlar',
          action: 'T\u00fcm notlar',
          emptyTitle: 'Hen\u00fcz not bulunmuyor',
          emptyDescription: 'Notlar g\u00fcncellendi\u011finde burada g\u00f6rebilirsin.',
          emptyAction: 'Notlar\u0131m\u0131 a\u00e7',
        },
      },
    },
    faculty: {
      stats: {
        sections: { label: 'Verdi\u011fin \u015eube', helper: 'Aktif ve planl\u0131' },
        students: { label: 'Toplam \u00d6\u011frenci', helper: '\u015eube bazl\u0131 toplam' },
        pending: { label: 'Bekleyen \u0130\u015flem', helperTemplate: 'Not: {grades} - Mazeret: {excuses}' },
      },
      sections: {
        upcoming: {
          title: 'Yakla\u015fan oturumlar',
          action: 'Oturumlar\u0131n\u0131 a\u00e7',
          emptyTitle: 'Oturum bulunmuyor',
          emptyDescription: 'Yakla\u015fan oturum eklenince listede g\u00f6receksin.',
          emptyAction: 'Oturum planla',
        },
        pending: {
          title: 'Bekleyen i\u015flemler',
          emptyTitle: 'Bekleyen i\u015flem yok',
          emptyDescription: 'Tamamlanacak \u00f6\u011fe bulunmuyor.',
          helperFallback: 'Tamamlanmay\u0131 bekliyor',
        },
      },
    },
    admin: {
      stats: {
        students: { label: '\u00d6\u011frenci Say\u0131s\u0131', helper: 'Aktif \u00f6\u011frenciler' },
        faculty: { label: 'Akademisyen', helper: 'Sistemdeki toplam' },
        courses: { label: 'Aktif Ders', helper: 'Bu d\u00f6nem' },
        sections: { label: 'Aktif \u015eube', helper: 'A\u00e7\u0131k \u015fube say\u0131s\u0131' },
      },
      sections: {
        systemStatus: {
          title: 'Sistem durumu',
          lastCheck: 'Son kontrol',
          uptime: 'Uptime',
          apiLabel: 'API',
          dbLabel: 'Database',
          uptimeUnit: 'sn',
        },
        activities: {
          title: 'Son aktiviteler',
          emptyTitle: 'Aktivite bulunmuyor',
          emptyDescription: 'Yeni hareketler burada listelenecek.',
          fallbackDetail: 'G\u00fcncelleme',
        },
      },
    },
  },
};

