export type AppRole = 'student' | 'faculty' | 'admin';

export const strings = {
  meta: {
    title: 'Smart Campus | ??renci ??leri Paneli',
    lang: 'tr',
    description: 'Smart Campus ile ders, yoklama ve not i?lerinizi tek panelden y?netin.',
    themeColor: '#1f3d7a',
  },
  brand: {
    name: 'Smart Campus',
    tagline: '??renci ??leri Paneli',
  },
  roles: {
    student: '??renci',
    faculty: 'Akademisyen',
    admin: 'Y?netici',
  } as Record<AppRole, string>,
  common: {
    userFallback: 'Kullan?c?',
    menuAriaLabel: 'Men?',
    openMenuLabel: 'Men?y? a?',
    closeMenuLabel: 'Men?y? kapat',
    userMenuLabel: 'Kullan?c? men?s?',
    loading: 'Y?kleniyor...',
    format: {
      timeFallback: '--:--',
      dateTimeFallback: '-',
    },
  },
  errors: {
    missingApiBase: {
      title: 'Sunucu ayar? eksik',
      message: 'VITE_API_BASE_URL tan?ml? de?il. L?tfen ortam de?i?kenini g?ncelleyip sayfay? yenileyin.',
      action: 'Sayfay? yenile',
    },
    boundary: {
      title: 'Bir ?ey ters gitti',
      description: 'Beklenmeyen bir hata nedeniyle sayfa y?klenemedi.',
      unexpected: 'Beklenmeyen bir hata olu?tu.',
      reload: 'Sayfay? yenile',
    },
  },
  navbar: {
    profile: 'Profil',
    logout: '??k?? yap',
    login: 'Giri?',
    register: 'Kay?t ol',
  },
  sidebar: {
    sections: {
      general: 'Genel',
      academic: 'Akademik',
      grades: 'Notlar',
      attendance: 'Yoklama',
      admin: 'Y?netim',
    },
    items: {
      dashboard: 'Panel',
      profile: 'Profil',
      courses: 'Dersler',
      sections: '?ubeler',
      myEnrollments: 'Kay?tlar?m',
      mySchedule: 'Program?m',
      sectionStudents: '?ube ??rencileri',
      myGrades: 'Notlar?m',
      transcript: 'Transkript',
      gradeEntry: 'Not Giri?i',
      gradeBulk: 'Toplu Not Giri?i',
      attendanceCheckIn: 'Yoklama Ver',
      attendanceSummary: 'Yoklama ?zeti',
      attendanceExcuse: 'Mazeret G?nder',
      attendanceSessions: 'Oturumlar',
      attendanceReport: 'Yoklama Raporu',
      attendanceReview: 'Mazeret ?ncele',
      courseAdmin: 'Ders Y?netimi',
      sectionAdmin: '?ube Y?netimi',
      users: 'Kullan?c?lar',
    },
  },
  auth: {
    login: {
      title: 'Tekrar ho? geldiniz',
      subtitle: 'Hesab?n?za giri? yap?n',
      cta: 'Hesab?n yok mu?',
      emailLabel: 'E-posta',
      emailPlaceholder: 'ornek@kampus.com',
      passwordLabel: '?ifre',
      passwordPlaceholder: '********',
      remember: 'Beni hat?rla',
      forgot: '?ifremi unuttum',
      submit: 'Giri? yap',
      submitting: 'Giri? yap?l?yor...',
      error: 'Giri? ba?ar?s?z.',
    },
    register: {
      title: 'Yeni hesap olu?tur',
      subtitle: '??renci veya akademisyen olarak kay?t olun',
      cta: 'Zaten hesab?n?z var m??',
      success: 'Kay?t ba?ar?l?. L?tfen e-postan?z? do?rulama i?in kontrol edin.',
      error: 'Kay?t ba?ar?s?z.',
      departments: {
        loadError: 'B?l?mler y?klenemedi. L?tfen daha sonra tekrar deneyin.',
        reloadError: 'B?l?mler g?ncellenemedi. L?tfen tekrar deneyin.',
      },
      labels: {
        firstName: '?sim',
        lastName: 'Soyisim',
        email: 'E-posta',
        role: 'Rol',
        department: 'B?l?m',
        password: '?ifre',
        confirmPassword: '?ifre Tekrar',
        studentNumber: '??renci Numaras?',
        employeeNumber: 'Personel Numaras?',
        title: 'Unvan',
        terms: 'Kullan?m ?artlar?n? kabul ediyorum',
        select: 'Se?iniz',
      },
      placeholders: {
        firstName: 'Ad?n?z? girin',
        lastName: 'Soyad?n?z? girin',
        email: 'ornek@universite.edu.tr',
        password: '********',
        confirmPassword: '********',
        studentNumber: '??renci numaran?z',
        employeeNumber: 'Personel numaran?z',
        title: 'Dr. ??r. ?yesi',
      },
      submit: 'Hesap Olu?tur',
      submitting: 'Kay?t oluyor...',
    },
    forgotPassword: {
      title: '?ifre S?f?rlama',
      subtitle: 'E-posta adresinizi girin; kay?tl?ysa s?f?rlama linki g?nderilecektir.',
      success: 'E?er bu e-posta kay?tl?ysa, ?ifre s?f?rlama linki g?nderildi.',
      error: '??lem s?ras?nda bir hata olu?tu.',
      submit: 'S?f?rlama linki g?nder',
      submitting: 'G?nderiliyor...',
      backToLogin: 'Giri? sayfas?na d?n',
    },
    resetPassword: {
      title: 'Yeni ?ifre Belirle',
      subtitle: 'G??l? bir ?ifre olu?turun.',
      success: '?ifreniz g?ncellendi. Giri? sayfas?na y?nlendiriliyorsunuz...',
      error: '?ifre g?ncellenemedi.',
      submit: '?ifreyi G?ncelle',
      submitting: 'G?ncelleniyor...',
      passwordLabel: 'Yeni ?ifre',
      confirmLabel: 'Yeni ?ifre Tekrar',
      backToLogin: 'Giri? sayfas?na d?n',
    },
    verifyEmail: {
      title: 'E-posta Do?rulama',
      subtitle: 'Hesab?n?z? do?ruluyoruz.',
      success: 'E-posta do?ruland?, birka? saniye i?inde giri? sayfas?na y?nlendirileceksiniz.',
      error: 'Ge?ersiz veya s?resi dolmu? do?rulama linki.',
      loading: 'Do?rulan?yor...',
    },
  },
  dashboard: {
    error: 'Dashboard verileri al?n?rken bir hata olu?tu.',
    header: {
      greeting: 'Ho? geldin',
      subtitles: {
        student: 'Kay?tl? derslerin, notlar?n ve yoklama ?zetin burada.',
        faculty: '?ubeler, yoklama ve not i?lemleri i?in h?zl? ?zet.',
        admin: 'Kamp?steki metrikler, sistem durumu ve son hareketler.',
        fallback: 'G?ncel bilgiler ve i?lemler burada.',
      },
    },
    trend: {
      up: 'Art??',
      down: 'D????',
    },
    quickActions: {
      student: [
        { label: 'Program?n? g?r', to: '/enrollments/schedule' },
        { label: 'Yoklama ver', to: '/attendance/checkin' },
      ],
      faculty: [
        { label: 'Oturumlar', to: '/attendance/sessions' },
        { label: 'Not giri?i', to: '/faculty/grades/entry' },
      ],
      admin: [
        { label: 'Kullan?c?lar', to: '/admin/users' },
        { label: 'Ders y?netimi', to: '/admin/courses/new' },
      ],
    },
    labels: {
      section: '?ube',
      planned: 'Planl?',
      awaiting: 'Bekliyor',
      inProgress: 'Devam ediyor',
      upcoming: 'Yakla?an',
      midterm: 'Vize',
      final: 'Final',
      gradePoint: 'Not Ort.',
      updatedAt: 'G?ncelleme',
    },
    student: {
      stats: {
        courses: { label: 'Kay?tl? Ders', helper: 'Aktif ve tamamlanan kay?tlar' },
        gpa: { label: 'GPA', helperPrefix: 'CGPA' },
        attendance: { label: 'Devam Oran?', helper: 'Genel ortalama' },
        today: { label: 'Bug?nk? Ders', helper: 'G?n?n program?' },
      },
      sections: {
        todayClasses: {
          title: 'Bug?nk? dersler',
          action: 'Ders program?n? a?',
          emptyTitle: 'Bug?n ders yok',
          emptyDescription: 'Takvimine yeni ders eklenince burada g?rebilirsin.',
          emptyAction: 'Program?n? g?r',
        },
        recentGrades: {
          title: 'Son notlar',
          action: 'T?m notlar',
          emptyTitle: 'Hen?z not bulunmuyor',
          emptyDescription: 'Notlar g?ncellendi?inde burada g?rebilirsin.',
          emptyAction: 'Notlar?m? a?',
        },
      },
    },
    faculty: {
      stats: {
        sections: { label: 'Verdi?in ?ube', helper: 'Aktif ve planl?' },
        students: { label: 'Toplam ??renci', helper: '?ube bazl? toplam' },
        pending: { label: 'Bekleyen ??lem', helperTemplate: 'Not: {grades} - Mazeret: {excuses}' },
      },
      sections: {
        upcoming: {
          title: 'Yakla?an oturumlar',
          action: 'Oturumlar?n? a?',
          emptyTitle: 'Oturum bulunmuyor',
          emptyDescription: 'Yakla?an oturum eklenince listede g?receksin.',
          emptyAction: 'Oturum planla',
        },
        pending: {
          title: 'Bekleyen i?lemler',
          emptyTitle: 'Bekleyen i?lem yok',
          emptyDescription: 'Tamamlanacak ??e bulunmuyor.',
          helperFallback: 'Tamamlanmay? bekliyor',
        },
      },
    },
    admin: {
      stats: {
        students: { label: '??renci Say?s?', helper: 'Aktif ??renciler' },
        faculty: { label: 'Akademisyen', helper: 'Sistemdeki toplam' },
        courses: { label: 'Aktif Ders', helper: 'Bu d?nem' },
        sections: { label: 'Aktif ?ube', helper: 'A??k ?ube say?s?' },
      },
      sections: {
        systemStatus: {
          title: 'Sistem durumu',
          lastCheck: 'Son kontrol',
          uptime: 'Uptime',
          apiLabel: 'API',
          dbLabel: 'Veritaban?',
          uptimeUnit: 'sn',
        },
        activities: {
          title: 'Son aktiviteler',
          emptyTitle: 'Aktivite bulunmuyor',
          emptyDescription: 'Yeni hareketler burada listelenecek.',
          fallbackDetail: 'G?ncelleme',
        },
      },
    },
  },
};
